#include <vector>
#include <string>

namespace Decompiler{
	namespace Skyrim {
		static const std::vector<std::string> EventNames = {
			"OnAnimationEvent", // ActiveMagicEffect
			"OnAnimationEventUnregistered", // ActiveMagicEffect
			"OnEffectFinish", // ActiveMagicEffect
			"OnEffectStart", // ActiveMagicEffect
			"OnGainLOS", // ActiveMagicEffect
			"OnLostLOS", // ActiveMagicEffect
			"OnUpdate", // ActiveMagicEffect
			"OnCombatStateChanged", // Actor
			"OnDeath", // Actor
			"OnDying", // Actor
			"OnEnterBleedout", // Actor
			"OnGetUp", // Actor
			"OnLocationChange", // Actor
			"OnLycanthropyStateChanged", // Actor
			"OnObjectEquipped", // Actor
			"OnObjectUnequipped", // Actor
			"OnPackageChange", // Actor
			"OnPackageEnd", // Actor
			"OnPackageStart", // Actor
			"OnPlayerBowShot", // Actor
			"OnPlayerFastTravelEnd", // Actor
			"OnPlayerLoadGame", // Actor
			"OnRaceSwitchComplete", // Actor
			"OnSit", // Actor
			"OnVampireFeed", // Actor
			"OnVampirismStateChanged", // Actor
			"OnAnimationEvent", // Alias
			"OnAnimationEventUnregistered", // Alias
			"OnGainLOS", // Alias
			"OnLostLOS", // Alias
			"OnReset", // Alias
			"OnUpdate", // Alias
			"OnAnimationEvent", // Form
			"OnAnimationEventUnregistered", // Form
			"OnGainLOS", // Form
			"OnLostLOS", // Form
			"OnSleepStart", // Form
			"OnSleepStop", // Form
			"OnTrackedStatsEvent", // Form
			"OnUpdate", // Form
			"OnUpdateGameTime", // Form
			"OnActivate", // ObjectReference
			"OnAttachedToCell", // ObjectReference
			"OnCellAttach", // ObjectReference
			"OnCellDetach", // ObjectReference
			"OnCellLoad", // ObjectReference
			"OnClose", // ObjectReference
			"OnContainerChanged", // ObjectReference
			"OnDestructionStageChanged", // ObjectReference
			"OnDetachedFromCell", // ObjectReference
			"OnEquipped", // ObjectReference
			"OnGrab", // ObjectReference
			"OnHit", // ObjectReference
			"OnItemAdded", // ObjectReference
			"OnItemRemoved", // ObjectReference
			"OnLoad", // ObjectReference
			"OnLockStateChanged", // ObjectReference
			"OnMagicEffectApply", // ObjectReference
			"OnOpen", // ObjectReference
			"OnRead", // ObjectReference
			"OnRelease", // ObjectReference
			"OnReset", // ObjectReference
			"OnSell", // ObjectReference
			"OnSpellCast", // ObjectReference
			"OnTranslationAlmostComplete", // ObjectReference
			"OnTranslationComplete", // ObjectReference
			"OnTranslationFailed", // ObjectReference
			"OnTrapHit", // ObjectReference
			"OnTrapHitStart", // ObjectReference
			"OnTrapHitStop", // ObjectReference
			"OnTrigger", // ObjectReference
			"OnTriggerEnter", // ObjectReference
			"OnTriggerLeave", // ObjectReference
			"OnUnequipped", // ObjectReference
			"OnUnload", // ObjectReference
			"OnWardHit", // ObjectReference
			"OnReset", // Quest
			"OnStoryActivateActor", // Quest
			"OnStoryAddToPlayer", // Quest
			"OnStoryArrest", // Quest
			"OnStoryAssaultActor", // Quest
			"OnStoryBribeNPC", // Quest
			"OnStoryCastMagic", // Quest
			"OnStoryChangeLocation", // Quest
			"OnStoryCraftItem", // Quest
			"OnStoryCrimeGold", // Quest
			"OnStoryCure", // Quest
			"OnStoryDialogue", // Quest
			"OnStoryDiscoverDeadBody", // Quest
			"OnStoryEscapeJail", // Quest
			"OnStoryFlatterNPC", // Quest
			"OnStoryHello", // Quest
			"OnStoryIncreaseLevel", // Quest
			"OnStoryIncreaseSkill", // Quest
			"OnStoryInfection", // Quest
			"OnStoryIntimidateNPC", // Quest
			"OnStoryJail", // Quest
			"OnStoryKillActor", // Quest
			"OnStoryNewVoicePower", // Quest
			"OnStoryPayFine", // Quest
			"OnStoryPickLock", // Quest
			"OnStoryPlayerGetsFavor", // Quest
			"OnStoryRelationshipChange", // Quest
			"OnStoryRemoveFromPlayer", // Quest
			"OnStoryScript", // Quest
			"OnStoryServedTime", // Quest
			"OnStoryTrespass", // Quest
			"OnBeginState",
			"OnEndState",
			"OnInit"
		};
        static const std::vector<std::string> EventNamesLowerCase = {
			"onanimationevent", // ActiveMagicEffect
			"onanimationeventunregistered", // ActiveMagicEffect
			"oneffectfinish", // ActiveMagicEffect
			"oneffectstart", // ActiveMagicEffect
			"ongainlos", // ActiveMagicEffect
			"onlostlos", // ActiveMagicEffect
			"onupdate", // ActiveMagicEffect
			"oncombatstatechanged", // Actor
			"ondeath", // Actor
			"ondying", // Actor
			"onenterbleedout", // Actor
			"ongetup", // Actor
			"onlocationchange", // Actor
			"onlycanthropystatechanged", // Actor
			"onobjectequipped", // Actor
			"onobjectunequipped", // Actor
			"onpackagechange", // Actor
			"onpackageend", // Actor
			"onpackagestart", // Actor
			"onplayerbowshot", // Actor
			"onplayerfasttravelend", // Actor
			"onplayerloadgame", // Actor
			"onraceswitchcomplete", // Actor
			"onsit", // Actor
			"onvampirefeed", // Actor
			"onvampirismstatechanged", // Actor
			"onanimationevent", // Alias
			"onanimationeventunregistered", // Alias
			"ongainlos", // Alias
			"onlostlos", // Alias
			"onreset", // Alias
			"onupdate", // Alias
			"onanimationevent", // Form
			"onanimationeventunregistered", // Form
			"ongainlos", // Form
			"onlostlos", // Form
			"onsleepstart", // Form
			"onsleepstop", // Form
			"ontrackedstatsevent", // Form
			"onupdate", // Form
			"onupdategametime", // Form
			"onactivate", // ObjectReference
			"onattachedtocell", // ObjectReference
			"oncellattach", // ObjectReference
			"oncelldetach", // ObjectReference
			"oncellload", // ObjectReference
			"onclose", // ObjectReference
			"oncontainerchanged", // ObjectReference
			"ondestructionstagechanged", // ObjectReference
			"ondetachedfromcell", // ObjectReference
			"onequipped", // ObjectReference
			"ongrab", // ObjectReference
			"onhit", // ObjectReference
			"onitemadded", // ObjectReference
			"onitemremoved", // ObjectReference
			"onload", // ObjectReference
			"onlockstatechanged", // ObjectReference
			"onmagiceffectapply", // ObjectReference
			"onopen", // ObjectReference
			"onread", // ObjectReference
			"onrelease", // ObjectReference
			"onreset", // ObjectReference
			"onsell", // ObjectReference
			"onspellcast", // ObjectReference
			"ontranslationalmostcomplete", // ObjectReference
			"ontranslationcomplete", // ObjectReference
			"ontranslationfailed", // ObjectReference
			"ontraphit", // ObjectReference
			"ontraphitstart", // ObjectReference
			"ontraphitstop", // ObjectReference
			"ontrigger", // ObjectReference
			"ontriggerenter", // ObjectReference
			"ontriggerleave", // ObjectReference
			"onunequipped", // ObjectReference
			"onunload", // ObjectReference
			"onwardhit", // ObjectReference
			"onreset", // Quest
			"onstoryactivateactor", // Quest
			"onstoryaddtoplayer", // Quest
			"onstoryarrest", // Quest
			"onstoryassaultactor", // Quest
			"onstorybribenpc", // Quest
			"onstorycastmagic", // Quest
			"onstorychangelocation", // Quest
			"onstorycraftitem", // Quest
			"onstorycrimegold", // Quest
			"onstorycure", // Quest
			"onstorydialogue", // Quest
			"onstorydiscoverdeadbody", // Quest
			"onstoryescapejail", // Quest
			"onstoryflatternpc", // Quest
			"onstoryhello", // Quest
			"onstoryincreaselevel", // Quest
			"onstoryincreaseskill", // Quest
			"onstoryinfection", // Quest
			"onstoryintimidatenpc", // Quest
			"onstoryjail", // Quest
			"onstorykillactor", // Quest
			"onstorynewvoicepower", // Quest
			"onstorypayfine", // Quest
			"onstorypicklock", // Quest
			"onstoryplayergetsfavor", // Quest
			"onstoryrelationshipchange", // Quest
			"onstoryremovefromplayer", // Quest
			"onstoryscript", // Quest
			"onstoryservedtime", // Quest
			"onstorytrespass", // Quest
			"onbeginstate",
			"onendstate",
			"oninit"
		};
	}
	namespace Fallout4{
		static const std::vector<std::string> EventNames = {
			"OnEffectFinish", // ActiveMagicEffect
			"OnEffectStart", // ActiveMagicEffect
			"OnCombatStateChanged", // Actor
			"OnCommandModeCompleteCommand", // Actor
			"OnCommandModeEnter", // Actor
			"OnCommandModeExit", // Actor
			"OnCommandModeGiveCommand", // Actor
			"OnCompanionDismiss", // Actor
			"OnConsciousnessStateChanged", // Actor
			"OnCripple", // Actor
			"OnDeath", // Actor
			"OnDeferredKill", // Actor
			"OnDifficultyChanged", // Actor
			"OnDying", // Actor
			"OnEnterBleedout", // Actor
			"OnEnterSneaking", // Actor
			"OnEscortWaitStart", // Actor
			"OnEscortWaitStop", // Actor
			"OnGetUp", // Actor
			"OnItemEquipped", // Actor
			"OnItemUnequipped", // Actor
			"OnKill", // Actor
			"OnLocationChange", // Actor
			"OnPackageChange", // Actor
			"OnPackageEnd", // Actor
			"OnPackageStart", // Actor
			"OnPartialCripple", // Actor
			"OnPickpocketFailed", // Actor
			"OnPlayerCreateRobot", // Actor
			"OnPlayerEnterVertibird", // Actor
			"OnPlayerFallLongDistance", // Actor
			"OnPlayerFireWeapon", // Actor
			"OnPlayerHealTeammate", // Actor
			"OnPlayerLoadGame", // Actor
			"OnPlayerModArmorWeapon", // Actor
			"OnPlayerModRobot", // Actor
			"OnPlayerSwimming", // Actor
			"OnPlayerUseWorkBench", // Actor
			"OnRaceSwitchComplete", // Actor
			"OnSit", // Actor
			"OnSpeechChallengeAvailable", // Actor
			"OnAliasInit", // Alias
			"OnAliasReset", // Alias
			"OnAliasShutdown", // Alias
			"OnLocationCleared", // Location
			"OnLocationLoaded", // Location
			"OnActivate", // ObjectReference
			"OnCellAttach", // ObjectReference
			"OnCellDetach", // ObjectReference
			"OnCellLoad", // ObjectReference
			"OnClose", // ObjectReference
			"OnContainerChanged", // ObjectReference
			"OnDestructionStageChanged", // ObjectReference
			"OnEquipped", // ObjectReference
			"OnExitFurniture", // ObjectReference
			"OnGrab", // ObjectReference
			"OnHolotapeChatter", // ObjectReference
			"OnHolotapePlay", // ObjectReference
			"OnItemAdded", // ObjectReference
			"OnItemRemoved", // ObjectReference
			"OnLoad", // ObjectReference
			"OnLockStateChanged", // ObjectReference
			"OnOpen", // ObjectReference
			"OnPipboyRadioDetection", // ObjectReference
			"OnPlayerDialogueTarget", // ObjectReference
			"OnPowerOff", // ObjectReference
			"OnPowerOn", // ObjectReference
			"OnRead", // ObjectReference
			"OnRelease", // ObjectReference
			"OnReset", // ObjectReference
			"OnSell", // ObjectReference
			"OnSpellCast", // ObjectReference
			"OnTranslationAlmostComplete", // ObjectReference
			"OnTranslationComplete", // ObjectReference
			"OnTranslationFailed", // ObjectReference
			"OnTrapHitStart", // ObjectReference
			"OnTrapHitStop", // ObjectReference
			"OnTriggerEnter", // ObjectReference
			"OnTriggerLeave", // ObjectReference
			"OnUnequipped", // ObjectReference
			"OnUnload", // ObjectReference
			"OnWorkshopMode", // ObjectReference
			"OnWorkshopNPCTransfer", // ObjectReference
			"OnWorkshopObjectDestroyed", // ObjectReference
			"OnWorkshopObjectGrabbed", // ObjectReference
			"OnWorkshopObjectMoved", // ObjectReference
			"OnWorkshopObjectPlaced", // ObjectReference
			"OnWorkshopObjectRepaired", // ObjectReference
			"OnChange", // Package
			"OnEnd", // Package
			"OnStart", // Package
			"OnEntryRun", // Perk
			"OnQuestInit", // Quest
			"OnQuestShutdown", // Quest
			"OnStageSet", // Quest
			"OnStoryIncreaseLevel", // Quest
			"OnAction", // Scene
			"OnBegin", // Scene
			"OnEnd", // Scene
			"OnPhaseBegin", // Scene
			"OnPhaseEnd", // Scene
			"OnAnimationEvent", // ScriptObject
			"OnAnimationEventUnregistered", // ScriptObject
			"OnBeginState", // ScriptObject
			"OnControlDown", // ScriptObject
			"OnControlUp", // ScriptObject
			"OnDistanceGreaterThan", // ScriptObject
			"OnDistanceLessThan", // ScriptObject
			"OnEndState", // ScriptObject
			"OnFurnitureEvent", // ScriptObject
			"OnGainLOS", // ScriptObject
			"OnHit", // ScriptObject
			"OnInit", // ScriptObject
			"OnKeyDown", // ScriptObject
			"OnKeyUp", // ScriptObject
			"OnLooksMenuEvent", // ScriptObject
			"OnLostLOS", // ScriptObject
			"OnMagicEffectApply", // ScriptObject
			"OnMenuOpenCloseEvent", // ScriptObject
			"OnPlayerCameraState", // ScriptObject
			"OnPlayerSleepStart", // ScriptObject
			"OnPlayerSleepStop", // ScriptObject
			"OnPlayerTeleport", // ScriptObject
			"OnPlayerWaitStart", // ScriptObject
			"OnPlayerWaitStop", // ScriptObject
			"OnRadiationDamage", // ScriptObject
			"OnTimer", // ScriptObject
			"OnTimerGameTime", // ScriptObject
			"OnTrackedStatsEvent", // ScriptObject
			"OnTutorialEvent", // ScriptObject
			"OnMenuItemRun", // Terminal
			"OnBegin", // TopicInfo
			"OnEnd", // TopicInfo
        };

		static const std::vector<std::string> EventNamesLowerCase = {
			"oneffectfinish", // ActiveMagicEffect
			"oneffectstart", // ActiveMagicEffect
			"oncombatstatechanged", // Actor
			"oncommandmodecompletecommand", // Actor
			"oncommandmodeenter", // Actor
			"oncommandmodeexit", // Actor
			"oncommandmodegivecommand", // Actor
			"oncompaniondismiss", // Actor
			"onconsciousnessstatechanged", // Actor
			"oncripple", // Actor
			"ondeath", // Actor
			"ondeferredkill", // Actor
			"ondifficultychanged", // Actor
			"ondying", // Actor
			"onenterbleedout", // Actor
			"onentersneaking", // Actor
			"onescortwaitstart", // Actor
			"onescortwaitstop", // Actor
			"ongetup", // Actor
			"onitemequipped", // Actor
			"onitemunequipped", // Actor
			"onkill", // Actor
			"onlocationchange", // Actor
			"onpackagechange", // Actor
			"onpackageend", // Actor
			"onpackagestart", // Actor
			"onpartialcripple", // Actor
			"onpickpocketfailed", // Actor
			"onplayercreaterobot", // Actor
			"onplayerentervertibird", // Actor
			"onplayerfalllongdistance", // Actor
			"onplayerfireweapon", // Actor
			"onplayerhealteammate", // Actor
			"onplayerloadgame", // Actor
			"onplayermodarmorweapon", // Actor
			"onplayermodrobot", // Actor
			"onplayerswimming", // Actor
			"onplayeruseworkbench", // Actor
			"onraceswitchcomplete", // Actor
			"onsit", // Actor
			"onspeechchallengeavailable", // Actor
			"onaliasinit", // Alias
			"onaliasreset", // Alias
			"onaliasshutdown", // Alias
			"onlocationcleared", // Location
			"onlocationloaded", // Location
			"onactivate", // ObjectReference
			"oncellattach", // ObjectReference
			"oncelldetach", // ObjectReference
			"oncellload", // ObjectReference
			"onclose", // ObjectReference
			"oncontainerchanged", // ObjectReference
			"ondestructionstagechanged", // ObjectReference
			"onequipped", // ObjectReference
			"onexitfurniture", // ObjectReference
			"ongrab", // ObjectReference
			"onholotapechatter", // ObjectReference
			"onholotapeplay", // ObjectReference
			"onitemadded", // ObjectReference
			"onitemremoved", // ObjectReference
			"onload", // ObjectReference
			"onlockstatechanged", // ObjectReference
			"onopen", // ObjectReference
			"onpipboyradiodetection", // ObjectReference
			"onplayerdialoguetarget", // ObjectReference
			"onpoweroff", // ObjectReference
			"onpoweron", // ObjectReference
			"onread", // ObjectReference
			"onrelease", // ObjectReference
			"onreset", // ObjectReference
			"onsell", // ObjectReference
			"onspellcast", // ObjectReference
			"ontranslationalmostcomplete", // ObjectReference
			"ontranslationcomplete", // ObjectReference
			"ontranslationfailed", // ObjectReference
			"ontraphitstart", // ObjectReference
			"ontraphitstop", // ObjectReference
			"ontriggerenter", // ObjectReference
			"ontriggerleave", // ObjectReference
			"onunequipped", // ObjectReference
			"onunload", // ObjectReference
			"onworkshopmode", // ObjectReference
			"onworkshopnpctransfer", // ObjectReference
			"onworkshopobjectdestroyed", // ObjectReference
			"onworkshopobjectgrabbed", // ObjectReference
			"onworkshopobjectmoved", // ObjectReference
			"onworkshopobjectplaced", // ObjectReference
			"onworkshopobjectrepaired", // ObjectReference
			"onchange", // Package
			"onend", // Package
			"onstart", // Package
			"onentryrun", // Perk
			"onquestinit", // Quest
			"onquestshutdown", // Quest
			"onstageset", // Quest
			"onstoryincreaselevel", // Quest
			"onaction", // Scene
			"onbegin", // Scene
			"onend", // Scene
			"onphasebegin", // Scene
			"onphaseend", // Scene
			"onanimationevent", // ScriptObject
			"onanimationeventunregistered", // ScriptObject
			"onbeginstate", // ScriptObject
			"oncontroldown", // ScriptObject
			"oncontrolup", // ScriptObject
			"ondistancegreaterthan", // ScriptObject
			"ondistancelessthan", // ScriptObject
			"onendstate", // ScriptObject
			"onfurnitureevent", // ScriptObject
			"ongainlos", // ScriptObject
			"onhit", // ScriptObject
			"oninit", // ScriptObject
			"onkeydown", // ScriptObject
			"onkeyup", // ScriptObject
			"onlooksmenuevent", // ScriptObject
			"onlostlos", // ScriptObject
			"onmagiceffectapply", // ScriptObject
			"onmenuopencloseevent", // ScriptObject
			"onplayercamerastate", // ScriptObject
			"onplayersleepstart", // ScriptObject
			"onplayersleepstop", // ScriptObject
			"onplayerteleport", // ScriptObject
			"onplayerwaitstart", // ScriptObject
			"onplayerwaitstop", // ScriptObject
			"onradiationdamage", // ScriptObject
			"ontimer", // ScriptObject
			"ontimergametime", // ScriptObject
			"ontrackedstatsevent", // ScriptObject
			"ontutorialevent", // ScriptObject
			"onmenuitemrun", // Terminal
			"onbegin", // TopicInfo
			"onend", // TopicInfo
		};
	}
}