#pragma once

#define CHAMPOLLION_VERSION_MAJOR 1
#define CHAMPOLLION_VERSION_MINOR 3
#define CHAMPOLLION_VERSION_PATCH 2

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define CHAMPOLLION_VERSION_STRING "v" MAKE_STR(CHAMPOLLION_VERSION_MAJOR) "." MAKE_STR(CHAMPOLLION_VERSION_MINOR) "." MAKE_STR(CHAMPOLLION_VERSION_PATCH)
